# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mageiaSyncUI.ui'
#
# Created: Sat Nov 22 10:27:11 2014
#      by: PyQt5 UI code generator 5.1.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(820, 587)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("share/icons/mageiasync.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.remoteDirLabel = QtWidgets.QLabel(self.centralwidget)
        self.remoteDirLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.remoteDirLabel.setObjectName("remoteDirLabel")
        self.verticalLayout.addWidget(self.remoteDirLabel)
        self.selectAll = QtWidgets.QPushButton(self.centralwidget)
        self.selectAll.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.selectAll.setObjectName("selectAll")
        self.verticalLayout.addWidget(self.selectAll)
        self.listIsos = QtWidgets.QListWidget(self.centralwidget)
        self.listIsos.setAlternatingRowColors(True)
        self.listIsos.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listIsos.setModelColumn(0)
        self.listIsos.setObjectName("listIsos")
        self.verticalLayout.addWidget(self.listIsos)
        self.localDirLabel = QtWidgets.QLabel(self.centralwidget)
        self.localDirLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.localDirLabel.setObjectName("localDirLabel")
        self.verticalLayout.addWidget(self.localDirLabel)
        self.localList = QtWidgets.QTableView(self.centralwidget)
        self.localList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.localList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.localList.setAlternatingRowColors(True)
        self.localList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.localList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.localList.setGridStyle(QtCore.Qt.DotLine)
        self.localList.setObjectName("localList")
        self.localList.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.localList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.IprogressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.IprogressBar.setEnabled(True)
        self.IprogressBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.IprogressBar.setProperty("value", 24)
        self.IprogressBar.setObjectName("IprogressBar")
        self.horizontalLayout_2.addWidget(self.IprogressBar)
        self.Lsize = QtWidgets.QLabel(self.centralwidget)
        self.Lsize.setObjectName("Lsize")
        self.horizontalLayout_2.addWidget(self.Lsize)
        self.speedLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.speedLCD.setObjectName("speedLCD")
        self.horizontalLayout_2.addWidget(self.speedLCD)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.timeRemaining = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeRemaining.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.timeRemaining.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeRemaining.setReadOnly(True)
        self.timeRemaining.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeRemaining.setObjectName("timeRemaining")
        self.horizontalLayout_2.addWidget(self.timeRemaining)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.syncGo = QtWidgets.QPushButton(self.centralwidget)
        self.syncGo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.syncGo.setObjectName("syncGo")
        self.horizontalLayout.addWidget(self.syncGo)
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.quit.setObjectName("quit")
        self.horizontalLayout.addWidget(self.quit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lvText = QtWidgets.QTextEdit(self.centralwidget)
        self.lvText.setReadOnly(True)
        self.lvText.setObjectName("lvText")
        self.verticalLayout.addWidget(self.lvText)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuFile.setObjectName("menuFile")
        self.menuSync = QtWidgets.QMenu(self.menubar)
        self.menuSync.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuSync.setObjectName("menuSync")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionUpdate = QtWidgets.QAction(mainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionQuit = QtWidgets.QAction(mainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPreferences = QtWidgets.QAction(mainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionRename = QtWidgets.QAction(mainWindow)
        self.actionRename.setObjectName("actionRename")
        self.actionCheck = QtWidgets.QAction(mainWindow)
        self.actionCheck.setObjectName("actionCheck")
        self.menuFile.addAction(self.actionUpdate)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionQuit)
        self.menuSync.addAction(self.actionRename)
        self.menuSync.addAction(self.actionCheck)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSync.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.syncGo, self.listIsos)
        mainWindow.setTabOrder(self.listIsos, self.stop)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MageiaSync"))
        self.remoteDirLabel.setText(_translate("mainWindow", "Remote directory"))
        self.selectAll.setText(_translate("mainWindow", "Select &All"))
        self.localDirLabel.setText(_translate("mainWindow", "Local directory:"))
        self.Lsize.setText(_translate("mainWindow", "0 bytes"))
        self.label_2.setText(_translate("mainWindow", "kB/s"))
        self.label_3.setText(_translate("mainWindow", "Remaining:"))
        self.timeRemaining.setDisplayFormat(_translate("mainWindow", "H:mm:ss"))
        self.syncGo.setText(_translate("mainWindow", "&Do sync"))
        self.stop.setText(_translate("mainWindow", "&Stop"))
        self.quit.setText(_translate("mainWindow", "&Quit"))
        self.label.setText(_translate("mainWindow", "Report"))
        self.menuFile.setTitle(_translate("mainWindow", "&File"))
        self.menuSync.setTitle(_translate("mainWindow", "S&ync"))
        self.actionUpdate.setText(_translate("mainWindow", "&Update list"))
        self.actionQuit.setText(_translate("mainWindow", "&Quit"))
        self.actionPreferences.setText(_translate("mainWindow", "&Preferences"))
        self.actionRename.setText(_translate("mainWindow", "&Rename archives"))
        self.actionCheck.setText(_translate("mainWindow", "&Check"))
        self.actionCheck.setToolTip(_translate("mainWindow", "Check selected images"))

